\Sexpr{set_parent('../Thesis.Rnw')}
\section{Choosing a Game}

%=====================================================================================================================%
% Chapter on pd, etc.
%=====================================================================================================================%

---PD or snowdrift: problems getting cooperation to evolve, more complicated